name: push-install-script

on:
  push:
    branches:
      - main
    paths:
      - scripts/install.sh

jobs:
  push-install-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: scripts/install.sh
          DEST_DIR: install.sh
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
