name: push-install-script

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - scripts/install.sh

jobs:
  push-install-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload to S3
        uses: ryand56/r2-upload-action@v1.4
        with:
          source-dir: |
           scripts/install.sh
           
          destination-dir: ./
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
