name: Build and Push Docker Image

permissions:
  id-token: write
  contents: read
  packages: write
  actions: read
  security-events: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - docs/**
      # - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        id: build-and-push
        with:
          context: .
          push: true
          pull: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1
        with:
          cosign-release: 'v2.4.3'
      - name: Check install!
        run: cosign version

      - name: Sign Images
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

      - name: Setup crane
        uses: imjasonh/setup-crane@v0.4

      - name: Copy image to latest tag
        if: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-rc') }}
        run: |
          crane tag ghcr.io/${{ github.repository }}:${{ github.ref_name }} latest
