name: main-release
concurrency:
  group: main-release
  cancel-in-progress: true
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
jobs:
  main-release:
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.23"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2.9'
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: releases
          DEST_DIR: cli
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}